### ISSUE TITLE
CONFIG_BPF_SYSCALL is undefined

### ISSUE THREAD

**Issue by Linuxuser4** [joelagnel/adeb#10]
Hi,
I am trying to get adeb-BCC working on a Hikey970 android platform. This has 4.9 kernel flashed. I got the BCC compiled in adeb environment.
I built the kernel with required configurations enabled in kernel as per the page https://github.com/joelagnel/adeb/blob/master/BCC.md. I made sure CONFIG_BPF_SYSCALL is enabled by putting a kernel print.
But, any BCC tool I use including hello_world.py complains that CONFIG_BPF_SYSCALL is not enabled. Below is detailed log. Any pointers would be of great help !

root@localhost:/# /usr/share/bcc/examples/hello_world.py 
In file included from <built-in>:3:
/virtual/include/bcc/helpers.h:26:2: error: "CONFIG_BPF_SYSCALL is undefined, please check your .config or ask your Linux distro to enable this feature"
#error "CONFIG_BPF_SYSCALL is undefined, please check your .config or ask your Linux distro to enable this feature"
 ^
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/examples/hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
root@localhost:/#

**Comment by joelagnel** [comment]
You need CONFIG_BPF_SYSCALL enabled and your kernel re-built with that, as
the error message says.

**Comment by Linuxuser4** [comment]
I realized the mistake. I had to remove adeb and reinstall adeb with new kernel path. This makes sure new kernel headers are used. Even though new kernel is flashed, header also needs to be updated in androdeb in target.

**Comment by joelagnel** [comment]
Feel free to follow up with this on BCC's issue list, or send a patch there if you feel something needs fixing there, your contribution there and here are appreciated! Closing this for now.

**Comment by CodeForeverZou** [comment]
uname -r get the system kernel version,
is different with the built kernel version.
you need to build the kernel which same with the 'uname -r'
